### ISSUE TITLE
sudo -i in run-as-user breaks WORKDIR for containers

### ISSUE THREAD

**Issue by smelchior** [mkenney/docker-scripts#8]
Your recent change to this:
https://github.com/mkenney/docker-scripts/blob/5e79644a8170c062be773f8c1a9679e70193bdba/container/run-as-user#L55

broke some of our builds as we are using the npm containers. The `sudo -i` changes the directory to be /home/dev/. Before it used to be /src/

**Comment by mkenney** [comment]
Hi @smelchior,

That's correct. There is an issue with `yarn` (and possibly other tools) in the `debian` images, in order to get a recent version of `yarn` installed in `debian` you need to use the [installer from yarnpkg.com](https://github.com/mkenney/docker-npm/blob/master/node-debian/Dockerfile#L50) which places the executables and associated metadata in the user's home directory (instead of `/usr/local/bin`) and adds the path to the `.bashrc` file.

Without the `-i` flag, sudo will not source the `.bashrc` file so `yarn` isn't available in the `dev` user's path. The fix is to add the `-i` flag and move the logic for dropping into `/src` into the user's profile.

All of the images have been updated, though there was a short gap last night where a build could have been produced without the extra logic, but I thought I had caught them before they went out.

Regardless, all the Dockerfiles have been updated and all tests are passing with the updated `run-as-user` script. I've [kicked off new builds](https://hub.docker.com/r/mkenney/npm/builds/) in Docker Hub to make sure any "bad" images get updated. When those are finished, you should be able to just pull the updated image and things should work normally.

Please let me know if you still have any trouble, thanks!

**Comment by mkenney** [comment]
Oh, and this is how that problem is solved if you're building your own images:

https://github.com/mkenney/docker-npm/blob/master/node-debian/Dockerfile#L79

**Comment by smelchior** [comment]
Hi @mkenney!  Thanks for your detailed explanation 👍! I pulled the image again and that fixed it, so i guess i was just a bit unlucky to pull during the transition time.
